package com.example.mysignupapp;

/**
 * Firebase Realtime Database model for an ambulance.
 * Stored under: ambulances/{ambulanceId}/
 *
 * ambulanceId is generated by push() so it is unique per record.
 */
public class Ambulance_model {

    private String ambulanceId;
    private String plateNo;
    private String type;           // "BLS" | "ALS" | "ICU"
    private String equipmentLevel; // "basic" | "full"
    private String equipmentNotes; // free-text description of contents
    private double costPerTrip;    // cost in local currency (TZS)
    private String status;         // "available" | "on_trip" | "maintenance"
    private String assignedDriver; // driver phone — empty string if unassigned
    private String driverName;     // cached for quick display
    private String hospitalId;     // admin phone who owns this ambulance
    private String hospitalName;   // cached org name
    private long   createdAt;

    // Required no-arg constructor for Firebase
    public Ambulance_model() {}

    public Ambulance_model(String ambulanceId, String plateNo, String type,
                            String equipmentLevel, String equipmentNotes,
                            double costPerTrip, String status,
                            String assignedDriver, String driverName,
                            String hospitalId, String hospitalName) {
        this.ambulanceId     = ambulanceId;
        this.plateNo         = plateNo;
        this.type            = type;
        this.equipmentLevel  = equipmentLevel;
        this.equipmentNotes  = equipmentNotes;
        this.costPerTrip     = costPerTrip;
        this.status          = status;
        this.assignedDriver  = assignedDriver;
        this.driverName      = driverName;
        this.hospitalId      = hospitalId;
        this.hospitalName    = hospitalName;
        this.createdAt       = System.currentTimeMillis();
    }

    // ── Getters & Setters ─────────────────────────────────────────────────────

    public String getAmbulanceId() { return ambulanceId; }
    public void setAmbulanceId(String v) { this.ambulanceId = v; }

    public String getPlateNo() { return plateNo; }
    public void setPlateNo(String v) { this.plateNo = v; }

    public String getType() { return type; }
    public void setType(String v) { this.type = v; }

    public String getEquipmentLevel() { return equipmentLevel; }
    public void setEquipmentLevel(String v) { this.equipmentLevel = v; }

    public String getEquipmentNotes() { return equipmentNotes; }
    public void setEquipmentNotes(String v) { this.equipmentNotes = v; }

    public double getCostPerTrip() { return costPerTrip; }
    public void setCostPerTrip(double v) { this.costPerTrip = v; }

    public String getStatus() { return status; }
    public void setStatus(String v) { this.status = v; }

    public String getAssignedDriver() { return assignedDriver; }
    public void setAssignedDriver(String v) { this.assignedDriver = v; }

    public String getDriverName() { return driverName; }
    public void setDriverName(String v) { this.driverName = v; }

    public String getHospitalId() { return hospitalId; }
    public void setHospitalId(String v) { this.hospitalId = v; }

    public String getHospitalName() { return hospitalName; }
    public void setHospitalName(String v) { this.hospitalName = v; }

    public long getCreatedAt() { return createdAt; }
    public void setCreatedAt(long v) { this.createdAt = v; }

    // ── Convenience helpers ───────────────────────────────────────────────────

    /** Returns true when no driver is currently assigned. */
    public boolean isUnassigned() {
        return assignedDriver == null || assignedDriver.isEmpty();
    }

    /** Human-readable cost string. */
    public String getCostDisplay() {
        if (costPerTrip <= 0) return "Free";
        return String.format("TZS %,.0f", costPerTrip);
    }
}
